### PR TITLE
[Ticket#12] Tick Timer 0

### PR DESCRIPTION
**Pull request by paweo90**
-Add Tick Timer 0 function

### CODE REVIEW

**Comment by dsalychev** [comment]
It seems that you opened two identical pull request for the same set of changes. Moreover, I will be able to accept no one of them because of conflicts. You have modified files which don't exist anymore in the base repository.

**Comment by dsalychev** [comment]
Well, it's ended as a complete mess. There are your commits mixed with the commits from the base repository. Please, create a patch (or several patches) and attach them here or share on a mailing list for developers.

**Comment by dsalychev** [comment]
Closed by the patch `0.1.99`: https://github.com/dsalychev/mcusim/commit/4103d4384a2e84e1b70d11e5578419c03b1c7427

**Comment by dsalychev** [comment]
@paweo90, you've forgotten to update a header file _mcusim/avr/sim/m328p.h_ to mention a new function to tick timers. Take a look: https://github.com/dsalychev/mcusim/commit/4103d4384a2e84e1b70d11e5578419c03b1c7427#diff-fa96228ff82e2411bb282edf64d2ea00

I've also prepare a list of commands which can be used to obtain a .patch file with the differencies between master branch of your fork and a master branch of the base repository. I used them on my own to create such patch file: 
[create-patch-between-forkmaster-and-upstreammaster.txt](https://github.com/dsalychev/mcusim/files/2459696/create-patch-between-forkmaster-and-upstreammaster.txt)

**Comment by paweo90** [comment]
Thank you for support with this messy pull request! Next pull request will not have so many awful commits!

**Pull request closed without merging**
