### PR TITLE
Correct 32-bit CALL and JMP decoding

### PR DESCRIPTION
**Pull request by kulp**
It appears as though support for 32-bit JMP and CALL instructions is incorrect. This becomes obvious when compiling for ATmega328, which, at least for me, uses JMP instead of RJMP in the vector table. The problem is basically of wrong endianness.

I have created a very simple test for ATmega328 support. Initially the test fails, but with fixes to JMP and CALL decoding, it succeeds.

I know that I did not select a clock frequency, but this is the configuration that `mcusim-config` gives if you allow it to provide the "default" clock frequency.

Before:
```
kulp@libra build((c32a47a...)) $ make tests
[100%] Generating TESTS
-- [TEST]: <redacted>/mcusim/tests/ATMEGA328-output-toggle/test
[!]: Frequency 0.0 kHz cannot be selected as a clock source
mcusim 0.1.96 : Microcontroller-based circuit simulator
Please find documentation at https://trac.mcusim.org
Please file your bug-reports at https://trac.mcusim.org/newticket
[PORTB checker] MCU clock: 1000.0kHz
[PORTB checker] MCU clock period: 1.0us
                  Model: ATmega328
              Signature: 1E9514
        Clock frequency: 1000.0 kHz
         Program memory: 0x0-0x3FFF words
     Bootloader section: 0x3800-0x3FFF words
            Data memory: 0x100-0x8FF bytes
                 EEPROM: 0x0-0x3FF bytes
                     PC: 0x0 word
          Reset address: 0x0 word
Interrupt vectors table: 0x1 word
[PORTB checker] check 1
[e]: Program counter is out of scope: pc=0x340000, pc+1=0x340001, flash_addr=0x3FFFF
CMake Error at tests.cmake:42 (message):
  failed:
  <redacted>/mcusim/tests/ATMEGA328-output-toggle/test


make[3]: *** [tests/TESTS] Error 1
make[2]: *** [tests/CMakeFiles/tests.dir/all] Error 2
make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
make: *** [tests] Error 2
```

After:
```
kulp@libra build((8cdce9f...)) $ make tests
[100%] Generating TESTS
-- [TEST]: <redacted>/mcusim/tests/ATMEGA328-output-toggle/test
[!]: Frequency 0.0 kHz cannot be selected as a clock source
mcusim 0.1.96 : Microcontroller-based circuit simulator
Please find documentation at https://trac.mcusim.org
Please file your bug-reports at https://trac.mcusim.org/newticket
[PORTB checker] MCU clock: 1000.0kHz
[PORTB checker] MCU clock period: 1.0us
                  Model: ATmega328
              Signature: 1E9514
        Clock frequency: 1000.0 kHz
         Program memory: 0x0-0x3FFF words
     Bootloader section: 0x3800-0x3FFF words
            Data memory: 0x100-0x8FF bytes
                 EEPROM: 0x0-0x3FF bytes
                     PC: 0x0 word
          Reset address: 0x0 word
Interrupt vectors table: 0x1 word
[PORTB checker] check 1
[PORTB checker] check 2
[PORTB checker] check 3
[PORTB checker] ticks passed: 99
-- [END TEST]
```

### CODE REVIEW

**Comment by dsalychev** [comment]
Darren, thanks for your patch.

I've applied it in `0.1.97` with a multiplication replaced with a shift here: https://github.com/dsalychev/mcusim/commit/84a97b178426d7d01dc7c8a7cb08e410b625e394#diff-23fbac69e2e0af7ab3be9fd227e4e04cR2037 and here: https://github.com/dsalychev/mcusim/commit/84a97b178426d7d01dc7c8a7cb08e410b625e394#diff-23fbac69e2e0af7ab3be9fd227e4e04cR2339 and a disassembled version of `firmware.hex`.

**Comment by kulp** [comment]
Certainly I am fine with your changes. I originally wrote the patch with a shift, but then I changed  `c << 1` to `c * 2` based on the other cases in `avr_decoder.c` where you use expressions like `mcu->pc = (unsigned long)(((long) mcu->pc) + (c + 1) * 2);`.

In any case, any modern compiler will produce the same code from the two expressions, so it is really a matter of taste.

Thanks for accepting my patch. I look forward to continuing to use mcusim.

**Comment by dsalychev** [comment]
I agree that it's a matter of taste. AVR decoder was almost the first thing I implemented within a simulator. I was in a hurry in order to receive something with a minimal functionality, I'd say. That's probably why a lot of mistakes is there.

Anyway, thanks for your interest and don't hesitate to ask any related questions. Would you mind if I ask you to use https://trac.mcusim.org for any future problems/issues and so on? Personally, I don't trust GitHub so much and want to keep development process as independent as possible.

**Comment by kulp** [comment]
After a few failures, I managed to create an account on your `trac` server (it was not obvious what the requirements for a username were, so `kulp` and my email address were both rejected without enough explanation -- not very friendly).

I will consider submitting future patches on `trac`, but to be honest, I am less inclined to contribute if I have to use a clunky web interface to upload patches one by one.

**Comment by dsalychev** [comment]
There are several places where you can share patches including github, trac.mcusim.org or a mailing list for developers. You may use one which suits you best.

**Comment by kulp** [comment]
How would one share patches on GitHub ? or do you mean that pull requests on GitHub are acceptable, though not preferred ?

**Comment by dsalychev** [comment]
I generally agree with this comment: https://github.com/torvalds/linux/pull/17#issuecomment-5654674. Moreover, pull requests weren't supposed to be a changes sharing tool initially in the minds of Git developers. I've read about it some time ago, but cannot find a link again.

I have no luxury to reject some contributions just because they have inappropriate commits messages, so I'm accepting them in any form. I usually have to reset several commits from a pull requests to a list of "Changes not staged for commit". It's easy to review changes and make minor modifications or additions in this case. And a single commit with all of these changes included and an correct message will be created only after that. That's why I start all of the messages with `patch X.Y.Z: ...`

> How would one share patches on GitHub ?

.patch file can be attached to an issue or even listed directly on any discussion.

> or do you mean that pull requests on GitHub are acceptable, though not preferred ?

That's correct.

**Pull request closed without merging**
